spring:
  application.name: franchise
  jackson.default-property-inclusion: NON_NULL
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
logging.level.org.springframework:
  data.repository: DEBUG
  r2dbc.core: DEBUG